name: Continuous Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server Docker Image
        working-directory: ./06-naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Docker Image
        working-directory: ./06-api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Microservice Jar
        working-directory: ./05-cambio-service
        run: mvn clean package -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./05-book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker compose build
